(source gnu)
(source melpa)
(source marmalade)

(depends-on "cask")
(depends-on "expand-region")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "popwin")
(depends-on "s")
(depends-on "smartparens")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "browse-kill-ring")
(depends-on "color-theme")
;; (depends-on "elscreen" :git "git@github.com:knu/elscreen.git")
(depends-on "rainbow-delimiters")
(depends-on "helm")
(depends-on "flycheck")
(depends-on "git-gutter")
(depends-on "popup")
(depends-on "powerline")
(depends-on "recentf-ext")
(depends-on "zlc")
(depends-on "auto-install")
(depends-on "init-loader")
(depends-on "key-chord")
(depends-on "smooth-scroll")
(depends-on "sequential-command")
(depends-on "yaml-mode")
(depends-on "bm")
(depends-on "color-moccur")
(depends-on "imenu")
(depends-on "direx")
(depends-on "anzu")
(depends-on "foreign-regexp")
(depends-on "helm-css-scss")
(depends-on "flymake-coffee")
(depends-on "highlight-indentation")
(depends-on "nodejs-repl")
(depends-on "smartrep")
(depends-on "epc")
(depends-on "rinari")
(depends-on "rainbow-mode")
(depends-on "zencoding-mode")
(depends-on "revive")
(depends-on "ac-helm")
(depends-on "tree-mode")
(depends-on "pod-mode")
(depends-on "jedi")
(depends-on "helm-descbinds")
(depends-on "windata")
(depends-on "flymake-ruby")
(depends-on "rbenv")
(depends-on "smart-newline" :git "git@github.com:ainame/smart-newline.el.git")
(depends-on "robe" :git "git@github.com:dgutov/robe.git")
(depends-on "key-combo")

;; prog modes
(depends-on "coffee-mode")
(depends-on "go-mode")
(depends-on "js2-mode")
(depends-on "json-mode")
(depends-on "less-css-mode")
(depends-on "motion-mode")
(depends-on "puppet-mode")
(depends-on "rhtml-mode")
(depends-on "ruby-mode")
(depends-on "haml-mode")
(depends-on "sass-mode")
(depends-on "slim-mode")

(depends-on "rubocop")
(depends-on "ruby-block")
(depends-on "ruby-electric")
(depends-on "ruby-end")

(depends-on "go-autocomplete")

;; theme
(depends-on "ample-zen-theme")

(depends-on "helm-git-files")
(depends-on "helm-ls-git")
(depends-on "scss-mode")